* managing growing projects with packages, crates, and modules
 [[https://doc.rust-lang.org/book/ch07-00-managing-growing-projects-with-packages-crates-and-modules.html][Managing Growing Projects with Packages, Crates, and Modules - The Rust Progr...]] 
  basically, how to organize code in larger projects
  - splitting code into multiple modules and multiple files
  - packages can contain more than one binary crate, and one optional library crate
  - stuff can be pulled out into separate crates as the project grows
  - we will also be going into scope more here
 
** features that allow for code organization
   - they describe it as "which details are exposed, which details are private, and what names are in scope"
   - I'm a bit unclear as to this exposed details / api / private concept in programming in general
  
*** packages: Cargo features that let you build, test, and share crates
    
*** crates: a tree of modules that produces a library or executable
    
*** modules and use: allow for organization, scope, and privacy of paths
    
*** paths: a way of naming an item - such as a struct, function, or module
    
* 7.1 packages and crates
 - crates:
 - package: one or more crates that provide a set of functionality
   - contains a =Cargo.toml= file containing the instructions for building the crates in the package
   - can have >= 0 binary crates, <=1 library crates, and must have at least one crate
     - {B, L ∈ ℕ | L ≤ 1, B + L > 0}

** cargo new
   - creates a =Cargo.toml= file
   - cargo file has the name of the package, version of cargo, and the edition
   - it doesn't mention src/main.rs because the convention is that =src/main.rs/ is "the crate root of a binary crate with the same name as the package"?
   - cargo also knows that if the package directory contains =src/lib.rs=, the package contains a library crate with the same name as the package that has =src/lib.rs/ as it's crate root
   - cargo passes crate root files (eg. src/main.rs, src/lib.rs) to ~rustc~ which builds the library or binary
   - with a brand-new project there will be only src/main.rs, therefore there is only one binary crate with the same name as the project
   - packages can have multiple binary crates by putting files in the src/bin directory -> each file will be a separate crate
   - 

** crates group functionality within a scope so that said functionality is easy to share between projects
   for example, the ~rand~ crate used in ch.2
   - this prevents name conflicts
   - we could access our struct named ~Rng~ and the ~rand~ crate's trait ~Rng~ because it is namespaced under ~rand::Rng~
   - 

* 7.2 modules: controlling scope and privacy
  - modules: organize code for legibility and reuse
  - paths: allow to for naming items
  - ~use~ : bring paths into scope
  - ~pub~ : make items public
  - ~as~ :
** public vs private privacy
- public: allows code to be used by outside code
- private: "internal implementation detail and not available to outside use"
* 7.3 Paths For Referring To An Item In The Module Tree
*** Example of using modules in a restaurant
    - front of house is where customers are, 
    - back of house is where chefs cook, people clean, managers do admin work

#+begin_src rust :tangle "restaurant/src/lib.rs"
#[cfg(test)]
mod tests {
    #[test]
    fn it_works() {
        let result = 2 + 2;
        assert_eq!(result, 4);
    }
}

mod front_of_house {
    fn add_to_waitlist() {}

    fn seat_at_table() {}

}

mod serving {
    fn take_order() {}

    fn serve_order() {}

    fn take_payment() {}
}

#+end_src
- modules are defined by starting with ~mod~ keyword
- modules can be nested
- modules can hold defs for structs, enums, constants, functions, etc
- modules allow for grouping related items and showing why they are related
- both src/main.rs and src/lib.rs are crate roots -> they complete a module called (in my case) ch7, at the root of the "module tree"

*** compilation of this section yields errrors
The messsages will say that the module ~hosting~ in private

*** modules define "privacy boundaries"
- to make structs, functions, etc. private you can put them in a module
- all items in rust are private by ddefault.
- items in parent modules /can't/ access private items in child modules
- items in child modules /can/ access items in "ancestor"(parent??) modules
- this is because child modules can see the context they're defined

*** Exposing paths with the ~pub~ keywordd
- below, we want to allow a function in the parent module to have access to a function in the child module
- we can change ~hosting~ to be public by adding ~pub~, but what is contained inside the module is still private
- pub on a module just makes it so that it can be referred to by ancestor modules
- to make a specific function, struct, piece of data public we must add the ~pub~ keyword in front of it too.
-
#+begin_src rust
mod front_of_house {
    pub mod hosting {
        pub fn add_to_waitlist() {}
    }
}

pub fn eat_at_restaurant() {
    // absolute  path
    crate::front_of_house::hosting::add_to_waitlist();

    // relative path
    front_of_house::hosting::add_to_waitlist();
}
#+end_src
- this will compile
- front_of_house is not public, BUT!
- because eat_at_restaurant function is defined in same moduole ads front of house,  we can refer to front of house from eat at restaurant
- ah, so theyre not both wrapped in a module statement but they are defined at the same "tier" in the same file, so therefoe they are siblings
- absolute paths star from the root of the craete's module tree which here is ~crate~?
- relative paths start from ~front_of_house~ -> since this is defined at the same level of eat at restaurant it....ah, hands are too cold. but iwll come backm to this later

  
  
*** starting relative patjhs wirth super
- super is described as being similkar to the ~..~ syntax
-
#+begin_src rust
fn serve_order() {}

mod back_of_house {
    fn fix_incorrect_order() {
        cook_order();
        super::serve_order();
    }
    fn cook_order() {}
}
#+end_src

ah, ok, so it gets us up to the parent module of back_of_house (*not* of ~fix_incorrect_order~)
- if we expect that all of these parts of stay in te samerelationshjip, that is, we expect thjat back_of_house and server_oder will remain within the same (file? module? relative relationship?), then writing ~super~ allows usto haveless code to update bwcuase we don't need to update the specific writing of a relative or absolute path

*** making structs and enums public

**** structs
- it is often useful for structs to have private fields
- there are some extra details in making structs adn enums public
- pub would make a stuct public but none of it's fields
- fields can be made individuallly publixc
- in te example below, we're modellinga  case wheree customers can pick they type of bread they want, but the fruit choice is ipto tje chef
- since the fruit can change quickly, customer's can't choose or see what they get
#+begin_src rust
mod back_of_house {
    pub struct Breakfast {
        pub toast: String,
        seasonal_fruit: String,
    }

    impl Breakfast {
        pub fn summer(toast: &str) -> Breakfast {
            Breakfast {
                toast: String::from(toast),
                seasonal_fruit: String::from("peaches"),
            }
        }
    }
}

pub fn eat_at_restaurant() {
    // Order a breakfast in the summer with Rye toast
    let mut meal = back_of_house::Breakfast::summer("Rye");
    // Change our mind about what bread we'd like
    meal.toast = String::from("Wheat");
    println!("I'd like {} toast please", meal.toast);

    // The next line won't compile if we uncomment it; we're not allowed
    // to see or modify the seasonal fruit that comes with the meal
    // meal.seasonal_fruit = String::from("blueberries");
}
#+end_src
- so here, 
  
**** enums
- it is basicaly never useful to have enums with private variants so by default they are public
- with enums, if we make an enum public all of its variants will become public as well

**** Example showing how making an enum public makes its variants public
#+begin_src rust
mod back_of_house {
    pub enum Appetizer {
        Soup,
        Salad,
    }
}

pub fn eat_at_restaurant() {
    let order1 = back_of_house::Appetizer::Soup;
    let order2 = back_of_house::Appetizer::Salad;
}
#+end_src

** next up: the ~use~ keyword, combining ~pub~ and ~use~
* 7.4 Bringing Paths into Scope with the ~use~ part Keyword
**  by using the ~use~ keyword, we can bring a path into scope once and then call the items in that path as if they were local items
#+begin_src rust
mod front_of_house {
    pub mod hosting {
        pub fn add_to_waitlist() {}
    }
}

use crate::front_of_house::hosting;

pub fn eat_at_restaurant() {
    hosting::add_to_waitlist;
    hosting::add_to_waitlist;
    hosting::add_to_waitlist;
}
#+end_src
- this process is described similar to creating a symbolic link in the filesystem.
- Adding ~use crate::front_of_house::hosting~ in the =crate root= brings ~hosting~ into scope as a local item
- this also will check the privacy
** you can also bring items into scope with ~use~ and a relative path
#+begin_src rust
/*--snip--*/

use self::front_of_house::hosting;

/*--snop--*/
#+end_src

** creating iodiomatic ~use~ paths: for functions, vs. structs
- WHat what is an idiom, again?
- you could also specify the entire path of the ~add_to_waitlist~ function e.g. ~crate::front_of_house::hosting::add_to_waitlist;~, but this would be "un-idiomatic?"
- having to specify the parent module when calling the function (eg. ~use crate::front_of_house::hosting;~, means that subsequent calls to the function will require specif
ying the function's source module when calling the function and makes it clear where that function is defined

- this behavior is *not* followed when calling in paths for structs, enums, and other items, however. The idiomatic way is to specify the full path.
#+begin_src rust
use std::collections::HashMap;

fn main() {
    let mut map = HashMap::new();
    map.insert(1, 2);
}
#+end_src

- this idiom has no strong reason behind this convention.
- the exception is when two things will have the same name: this won't be possible
- 

#+begin_src rust
use std::fmt; // this provides a Result
use std::io; // this also provides a Result

fn function1() -> fmt::Result {
    // --snip--
}

fn function2() -> io::Result<()> {
    // --snip
}
#+end_src
so, because here ~Result~ could be pulled from either module, we need to be explicit about which one we are going for.

** providing new names with the ~as~ keyword
#+begin_src rust
use std::fmt::Result;
use std::io::Result as IoResult;

fn function1() -> Result {
    // --snip
}

fn function2() -> IoResult<()> {
    // --snip
}
#+end_src
- yeah, so the above is just like python's ~use numpy as np~
- 

** re-exporting names with ~pub use~
- when a name is brought into scope with ~use~, the name in the new scope is private
- hmm, ok, so I should probably go through exactly what the implications of this are





** using external packages
- we can add external packages to our cargo.tom with 'rand = "0.8.3"'
- adding packages to cargo.toml tells cargo to download the ~rand~ package, as well as any dependencies
- then we can call ~rand~ into scope with a ~use~ line
- packages included in ~std~ (the standard library) don't need to be brought into scope in the same way, but we do still call them into scope using ~use~
-

**  using nested paths to clean up large ~use~ lists
- use lists like the one below can rapidly grow to take up large amounts of vertical space in code
#+begin_src rust
use std::cmp::Ordering;
use std::io;
// the quicker ways
use std::{cmp::Ordering, io};


// example 2
use std::io;
use std::io::Write;


// we can nest these two paths using self
use std::io;
use std::io::Write;
use std::io::{self,Write};
#+end_src

** The glob operator
- glob works like how I've seen it before: if we want to bring all public items defined in a path into scope, we can specify thta path followed by ~*~, the glob operator:
#+begin_src rust
use std::collections::*;
#+end_src
- the downside to glob is that it brings EVERYTHING under the path into scope
- this can make it harder to see what paths are within scope

* 7.5 Separating Modules Into Different Files
- all examples tus far have defined multiple modules in one file
- splitting them up when the modules get large can make them easier to navigate
- "in this case, the crate root is /src/lib.rs/ but this procedure also works with binary crates whose crate root file is /src/main.rs/"
#+begin_src rust :tangle "src/lib.rs"
mod front_of_house;

pub use crate::front_of_house::hosting

pub fn eat_at_restaurant() {
    hosting::add_to_waitlist();
    hosting::add_to_waitlist();
    hosting::add_to_waitlist();
}
#+end_src

    
- using a semicolon after ~mod front_of_house~ (rather than using a block?) tells rust to
  " load the contents of the module from another file with the same name as the module"
#+begin_src rust :tangle "src/front_of_house.rs"
pub mod hosting;
#+end_src
  - "to continue and extract the ~hosting~ module to it's own file as well we change /src/front_of_house.rs/ to contain only the declaration of the hosting module"
#+begin_src rust :tangle "src/front_of_house/hosting.rs"
pub fn add_to_waitlist() {}
#+end_src
- with the changes above, the module tree remains the same and the calls in ~eat_at_restaurant~ work without modifications, 
BUT the definitions live in different files
- this lets you move modules to new files as they grow in size
*** note
- ~pub use crate::front_of_house::hosting~ in /src/lib.rs/ also hasn't changed, nor does ~use~ have any impact on what files are complied aspartof the crate. 
- The ~mod~ keyword declares modules, and rust looks in a file with the same name as the module for the code that goes into that module
- Qn: is this the same as when the two things were identically named earlier on in the chapters?
- this will definitely feel more applicable when we're dealing with large projects: right now it's just showing us the basics of this method of organization
- 
AHH, RIGHT! if you look at a diagram of the directory structure, tje it makes sense


** Next up:
we will look at the collections in Ch. 8
